name: WorklowSample

run-name:  Run ${{ github.run_number }} - ${{ github.run_id }} - ${{ github.run_attempt }}  Deployed by ${{ github.actor }}

on:
 workflow_dispatch: #Manual trigger

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: echo "Hello "
 
