name: Matrix Example

on:
  workflow_dispatch:
 

jobs:
 TestMatrixJob: # Job ID
    strategy:
        matrix:
            os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
            node: [10, 12, 14]

    name: Testing Matrix Strategy # Job Name
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
