name: Work Flow to trigger on repo dispatch

on:
 # Trigger the workflow on repository_dispatch event
 # This event is triggered by the GitHub API PST request to repos/{owner}/{repo}/dispatches
 # Can have more than one event type. Base on even type at the time of trigger can choose steps to run in the workflow
 # Trigger only when in default branch
 # You need to generate token with repo scope and content write access to trigger this event
  repository_dispatch:
    types: [event1 , event2]


jobs:
    RepoDispatchJob:
        name: Repo Dispatch Event Job
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'repository_dispatch' }}
        steps:
         - name: First Event
           run: echo "Event 1 Triggered ${{github.event.action}}"
         - name: Second Event
           env:
             Message: ${{ github.event.client_payload.message }}
           if: ${{ github.event.action == 'event2' }}
           run: echo "Event 2 Triggered with message ${{ env.Message }}"
