name: Workflow B
on: 
  workflow_dispatch: #Manual trigger
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: echo "Running tests"
